export const ASSET_REGISTER_BULK_ASSIGN_MAX_VEHICLES = 50;

export const AssetRegisterAssignmentErrorCodes = {
  NO_ACTIVE_LEASE_CONTRACT: 'NO_ACTIVE_LEASE_CONTRACT',
  LEASE_CAPACITY_SHORTFALL: 'LEASE_CAPACITY_SHORTFALL',
  NO_MATCHING_ASSET_LINE: 'NO_MATCHING_ASSET_LINE',
  VEHICLE_NOT_ASSIGNABLE: 'VEHICLE_NOT_ASSIGNABLE',
  VEHICLE_ALREADY_ASSIGNED: 'VEHICLE_ALREADY_ASSIGNED',
  NO_ACTIVE_ASSIGNMENT: 'NO_ACTIVE_ASSIGNMENT',
  ORGANISATION_CLIENT_REQUIRED: 'ORGANISATION_CLIENT_REQUIRED',
  ORGANISATION_CLIENT_MISMATCH: 'ORGANISATION_CLIENT_MISMATCH',
} as const;
