export const ASSET_REGISTER_VEHICLE_REGISTRATION_MAX_LENGTH = 32;
export const ASSET_REGISTER_VEHICLE_CHASSIS_MAX_LENGTH = 64;
export const ASSET_REGISTER_VEHICLE_SPECIAL_NOTES_MAX_LENGTH = 2000;
export const ASSET_REGISTER_VEHICLE_DEACTIVATE_REASON_MAX_LENGTH = 500;
export const ASSET_REGISTER_VEHICLE_MODEL_YEAR_MIN = 1900;
export const ASSET_REGISTER_VEHICLE_MODEL_YEAR_MAX = 2100;
export const ASSET_REGISTER_VEHICLE_ODOMETER_MAX = 9_999_999;

export const ASSET_REGISTER_VEHICLE_OPERATIONAL_STATUSES = [
  'available',
  'leased',
  'workshop',
  'sold',
  'retired',
] as const;

export type AssetRegisterVehicleOperationalStatus =
  (typeof ASSET_REGISTER_VEHICLE_OPERATIONAL_STATUSES)[number];
